### ISSUE TITLE
Meta issue: translate ink! env library

### ISSUE THREAD

**Issue by clarus** [formal-land/coq-of-rust#87]
The goal is to have the file https://github.com/formal-land/coq-of-rust/blob/main/CoqOfRust/ink/Env.v type-checking in Coq. This is one of the libraries used to make `ink!` smart contracts. That would be a good milestone toward translating Rust smart contracts to Coq. Note that there are still other `ink!` libraries, and these libraries themselves depend on other files.

To translate this file successfully, we take all the Rust features that we do not handle but need to, and make a task on a smaller example. We use the label `Ink! env library`.

- [x] https://github.com/formal-land/coq-of-rust/issues/88
- [ ] https://github.com/formal-land/coq-of-rust/issues/89
- [x] https://github.com/formal-land/coq-of-rust/issues/90
- [x] https://github.com/formal-land/coq-of-rust/issues/95

**Comment by clarus** [comment]
Closing as not a priority anymore.
